# define the network
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# start the services section
services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
        - DOMAIN_NAME=${DOMAIN_NAME} # Use the variable from the .env file
    container_name: starfish-nginx
    tty: true
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  php:
    build:
      context: .
      dockerfile: .docker/php/fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
        - TARGET_PHP_VERSION=${PHP_VERSION}
    container_name: starfish-php
    hostname: php
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - vendor_data:${APP_CODE_PATH_CONTAINER}/vendor
    networks:
      - backend
    depends_on:
      - mysql

  app:
    build:
      context: .
      dockerfile: .docker/php/app/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
        - TARGET_PHP_VERSION=${PHP_VERSION}
    container_name: starfish-app
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - vendor_data:${APP_CODE_PATH_CONTAINER}/vendor
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
    networks:
      - backend

  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: envx
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: starfish
    container_name: starfish-mysql
    volumes:
      - db_data:/var/lib/mysql

volumes:
  vendor_data:
    driver: local
  db_data:
    driver: local