x-labels:
  com.starfish.name: StarfishEnvx

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: starfish-nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME} # Use the variable from the .env file
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssr:/var/www/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - php
    labels:
      com.starfish.role: nginx
      com.starfish.purpose: development
    networks:
      - starfish-network

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: starfish-php
    hostname: php
    volumes:
      - ./ssr:/var/www/app:delegated
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/check-health.sh" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      PHP_XDEBUG: 1
      APP_ENV: ${APP_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      com.starfish.role: php
      com.starfish.purpose: development
    networks:
      - starfish-network
networks:
  starfish-network:
    driver: bridge
