-- Create user and grant remote access
CREATE USER IF NOT EXISTS '${MYSQL_CLIENT_USER}'@'%' IDENTIFIED BY '${MYSQL_CLIENT_PASSWORD}';
-- GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_CLIENT_USER}'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_CLIENT_USER}'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
